### ISSUE TITLE
New Set Protocol Strategies 

### ISSUE THREAD

**Issue by samcampbe11** [SetProtocol/set-protocol-strategies#79]
Love what y'all are doing! My personal favorite is the 75%/25% BTC/ETC Set.  

A few new strategy suggestions:

- Dollar cost averaging (i.e., buy into a position over the course of a day, week, or year. A user could deposit $1,200 in DAI and each month invest $100 into BTC). 
- A market cap. & equal-weighted index for top 10 coins by market cap. (i.e., Bitwise Hold 10). 
- Time locked investments (either an initial period or withdrawal delay. More of a behavioral Buy & Hold strategy).
- A dividend style basket of investments (i.e., staked or interest bearing). 

I understand that some may be more technically complex given they involve other protocols. 

Thanks! 
-Sam

**Comment by richardliang** [comment]
Thanks for the suggestions!
